KTBM_Core_JSON = require("KTBM_Core_JSON.lua");

KTBM_FileUtils_CurrentlyActiveSaveIndex = 1;
KTBM_FileUitls_SubDirectory = "AliveInside\\"
KTBM_FileUtils_SavesDirectory = KTBM_FileUitls_SubDirectory .. "Saves\\"

KTBM_FileUtils_ActiveSave = nil;
KTBM_FileUtils_OptionsFile = nil;

KTBM_FileUtils_IsCurrentlyInitialized = false;

--Decodes a JSON file and returns the raw object. Useful for non-standard reads.
KTBM_Core_FileUtils_DecodeJSONFile = function(fileName) 
    local theFile = (io.open)(fileName, "r") --Open the file
    if theFile == nil then
        return nil;
    end

    local content = theFile:read("*all") --Read the file's content
    theFile:close()
    
    return KTBM_Core_JSON.decode(content) --Return the decoded file.
end

KTBM_Core_FileUtils_EncodeJSONFile = function(content, path)
    local theFile = (io.open)(KTBM_FileUitls_SubDirectory .. path .. ".json", "w")
    theFile:write(KTBM_Core_JSON.encode(content));
    theFile:close();
    return true;
end


KTBM_Core_FileUtils_SaveSetCheckpoint = function(checkpoint)
    if KTBM_FileUtils_OptionsFile == nil or KTBM_FileUtils_ActiveSave == nil then
        return false;
    end
    
    KTBM_FileUtils_ActiveSave.checkpoint = checkpoint;
    local saveFile = (io.open)(KTBM_FileUtils_SavesDirectory.."AliveInside-Save"..KTBM_FileUtils_OptionsFile.activeSaveFile..".json", "w")
    saveFile:write(KTBM_Core_JSON.encode(KTBM_FileUtils_ActiveSave));
    saveFile:close();    

    return true;
end

KTBM_Core_FileUtils_Init = function()
    if not KTBM_Core_FileUtils_DirectoryExists(KTBM_FileUitls_SubDirectory) then --Create File Tree
        print("Alive Inside SubDirectory Not Found! Creating...");
        os.execute("mkdir ".. KTBM_FileUtils_SavesDirectory);  
    end

    if not KTBM_Core_FileUtils_FileExists(KTBM_FileUitls_SubDirectory.."options.json") then
        print("Options file not found! Creating...")
        local gameOptions = (io.open)(KTBM_FileUitls_SubDirectory.."options.json", "w");
        gameOptions:write(KTBM_FileUtils_GenericOptionsFile);
        gameOptions:close();
    end

    KTBM_FileUtils_OptionsFile = KTBM_Core_FileUtils_DecodeJSONFile(KTBM_FileUitls_SubDirectory.."options.json");

    if not KTBM_Core_FileUtils_FileExists(KTBM_FileUtils_SavesDirectory.."AliveInside-Save"..KTBM_FileUtils_OptionsFile.activeSaveFile..".json") then
        print("Save file not found! Creating...")
        local saveFile = (io.open)(KTBM_FileUtils_SavesDirectory.."AliveInside-Save"..KTBM_FileUtils_OptionsFile.activeSaveFile..".json", "w")
        saveFile:write(KTBM_FileUtils_GenericSaveFile);
        saveFile:close();
    end

    KTBM_FileUtils_ActiveSave = KTBM_Core_FileUtils_DecodeJSONFile(KTBM_FileUtils_SavesDirectory.."AliveInside-Save"..KTBM_FileUtils_OptionsFile.activeSaveFile..".json");

    KTBM_FileUtils_IsCurrentlyInitialized = true;
    print("FileUtils Initialization Complete.") --We now have all requisite files and are ready to use them.
end

KTBM_Core_FileUtils_FileExists = function(file)
   local ok, err, code = os.rename(file, file)
   if not ok then
      if code == 13 then
         -- Permission denied, but it exists
         return true
      end
   end
   return ok, err
end

KTBM_Core_FileUtils_DirectoryExists = function(directory)
    return KTBM_Core_FileUtils_FileExists(directory)
end

KTBM_FileUtils_GenericOptionsFile = [[
{
  "warning": "Hello there! This file was automatically generated by Alive Inside. It's not recommended to modify it yourself!",
  "activeSaveFile": 1,
  "screenReaderCompat": false
}
]]

--[[
Save File Checkpoint Definitions:

0 - Not Yet Started
1 - Intro, Configurator Complete.
2 - Infinite Runner
3 - Infinite Runner End, School Reunion & Defense 
4 - School Hub
5 - Scavenging - Group 1 - Beach
6 - Scavenging - Group 2 - Greenhouse / Admin
7 - Finale
99 - Fully Completed.

--]]

KTBM_FileUtils_GenericSaveFile = [[
{
  "configurator": {
    "s2KilledKenny": false,
    "s2Wellington": false,
    "s2Alone": false,
    "s4KilledLilly": false,
    "s4SavedViolet": false,
    "s4TrustedAJ": false
  },
  "checkpoint": 0
}
]]

if KTBM_Core_Project_IsDebugMode then
    KTBM_FileUtils_GenericSaveFile = [[
    {
        "configurator": {
        "s2KilledKenny": false,
        "s2Wellington": false,
        "s2Alone": false,
        "s4KilledLilly": true,
        "s4SavedViolet": true,
        "s4TrustedAJ": false
        },
        "checkpoint": 1
    }
]]
end